server:
  port: 8081
  servlet:
    context-path: /payment

spring:
  application:
    name: payment
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3305/payment
    username: root
    password: docker